// build_options: 
Memory, Objects lifecycle
=========================
Arnauld Van Muysewinkel <avm@pendragon.be>
v0.1, 23-Nov-2016: Draft version
:backend: slidy
:data-uri:
ifdef::env-build[:icons: font]
:extension: adoc
//extension may be overriden by compile.sh
ifeval::["{extension}"!="pdf"]
:doctitle: Good Programming Practices for Performance - {doctitle}
:lastpage: lastpage.adoc.include
endif::[]
:copyright: Creative-Commons-Zero (Arnauld Van Muysewinkel)

Content
-------

* <<rate,Reduce allocation rate>>
* <<fragmentation,Avoid memory fragmentation>>
* <<stack,Use stack rather than heap>>
* <<gc,Avoid losing time with the GC>>
* <<_sessions,Sessions>>

_(link:0.1-training_plan.{extension}#_best_practices[back to plan])_


[[rate]]
Reduce allocation rate
----------------------

* useless allocation/deallocation: try to re-use objects -> consider using object pools
* big objects in memory (e.g. file transfer -> use streaming)
* avoid allocating objects in loops when they can be allocated only once before the loop


[[fragmentation]]
Avoid memory fragmentation
--------------------------

* prefer StringBuilder over '+' or String.format
* allocate collections/buffers/builders with appropriate initialCapacity


[[stack]]
Use stack rather than heap
--------------------------

* prefer local variables over class variables


[[gc]]
Avoid losing time with the GC
-----------------------------

* reduce memory pressure
** chase memory leaks
** keep your sessions small, or better: prefer session-less designs
** use SoftReference for long-lived objects
* don't +System.gc()+
* difficult: balance memory used vs. performance
** E.g.: reduce session scope as much as possible => more DB requests!

_See also https://github.com/arnauldvm/jpt-course[JPT] course_


Sessions
--------

NOTE: Sessions must be serializable:

* all objects under the session must be serializable (whole objects graph!)
* avoid big objects in the session
* Use DTO's

Actually, the potential issues are the same as for JSF ViewContext.


include::{lastpage}[]
