// build_options: 
Good Programming Practices for Performance -  Contentions (threads, locks...)
=============================================================================
Arnauld Van Muysewinkel <avm@pendragon.be>
v0.1, 23-Nov-2016: Draft version
:backend: slidy
:data-uri:
ifdef::env-build[:icons: font]
:extension: adoc
//extension may be overriden by compile.sh
ifeval::["{extension}"!="pdf"]
:lastpage: {lastpage}
endif::[]
:copyright: Creative-Commons-Zero (Arnauld Van Muysewinkel)

Content
-------

* <<_general_recommendations,General Recommendations>>
* <<jee,Thread management in Java EE>>
* <<_other_advices,Other advices>>

_(link:0.1-training_plan.{extension}#_best_practices[back to plan])_


General recommendations
-----------------------

NOTE: Never, ever, use non-final static variables

(Note: constants, loggers must be final static variables)


NOTE: Don't rely on default locale:

no Locale.setDefault(), no Locale.getDefault(), no new formatter without passing a Locale; see jdss wiki


[[jee]]
Thread management in Java EE
----------------------------

NOTE: Do not use _any_ concurrency control mechanism

like:

* synchronized keyword
* ConcurrentHashMap
* ThreadLocal
* etc.


Thread management in Java EE
----------------------------

*****
.Why is thread creation and management disallowed?*
[quote, "EJB Restrictions" (http://www.oracle.com/technetwork/java/restrictions-142267.html)]
_____
The EJB specification assigns to the EJB container the responsibility
for managing threads. Allowing enterprise bean instances to create and manage threads
would interfere with the container's ability to control its components' lifecycle.
Thread management is not a business function, it is an implementation detail,
and is typically complicated and platform-specific.
Letting the container manage threads relieves the enterprise bean developer
of dealing with threading issues. Multithreaded applications are still possible,
but control of multithreading is located in the container, not in the enterprise bean.
http://www.oracle.com/technetwork/java/restrictions-142267.html[>>>]
_____
*****


Other advices
-------------

http://www.javaperformancetuning.com/tips/synchronization.shtml

* avoid synchronization as much as possible -> consider "Lock-Free (or Lockless) Programming"
 http://preshing.com/20120612/an-introduction-to-lock-free-programming/
** never use +synchronized(this)+
* even using +volatile+ may be slow
* beware of Concurrent structures
* avoid using thread safe classes when not required (e.g. prefer StringBuilder over StringBuffer)!
* *never* use "exactly-once" QoS for messaging, use:
** at-most-once if you can afford losing messages
** at-least-once (+ message numbering) otherwise
* use async I/O if you can


include::{lastpage}[]
